version: "3.1"

services:
    mongo:
        restart: always
        container_name: mongo
        image: mongo
        working_dir: /usr/local/sampleCollections
        tty: true
        stdin_open: true
        ports:
          - 127.0.0.1:27017:27017
        volumes:
            - ./data:/data/db
            - ./collections/dbkoda-data/SampleCollections:/usr/local/sampleCollections
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    mongo-express:
        restart: always
        container_name: mongo-express
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 127.0.0.1:8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password

    node:
        container_name: node
        image: node
        user: node
        tty: true
        stdin_open: true
        working_dir: /home/node/app
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./client:/home/node/app

    server:
        image: node
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        environment:
            MONGO_USERNAME: admin
            MONGO_PASSWORD: password
            MONGO_DATABASE: SampleCollections
        volumes:
            - ./server:/home/node
