version: "3.1"

services:
    mongo:
        restart: always
        container_name: mongo
        image: mongo
        working_dir: /usr/local/sampleCollections
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
            - ./collections/dbkoda-data/SampleCollections:/usr/local/sampleCollections
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    mongo-express:
        restart: always
        container_name: mongo-express
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 127.0.0.1:8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
